### PR TITLE
More information on history of the clans app.

### PR DESCRIPTION
**Pull request by brendanjhart**
I wanted to change this FAF Clans history in the readme because the words make me sound bad, and my real name is here - so it can be found by searcher such as a new employer!

I reviewed the original discussion in the FAF Forum, and my memory was correct. 

http://forums.faforever.com/viewtopic.php?f=2&t=2881&start=60

So I updated the readme.

### CODE REVIEW

**Comment by IDragonfire** [comment]
I finished the application at the beginning of 2014 and it wass deployed before the ownerships changes. Since 2014 I no longer maintain the clannapp.
Currently I port the app to react:
https://github.com/FAForever/clans/tree/feat/react
and use a JAVA FAF API:
https://github.com/micheljung/faf-java-api/tree/feature/clan

**Comment by micheljung** [comment]
"faftools" is not an API, it wasn't created by ZeP and ZeP is no longer the main developer of FAF.

But either way; who cares about the history of this app, I would just remove the whole thing.

**Comment by brendanjhart** [comment]
MichealJung, I care because my real name is in there and the readme suggests I abandoned the work. The reality is I could not complete because I could not get any communication from Zep about integration.

**Comment by brendanjhart** [comment]
@IDragonfire So this new application will replace the old Clans? Cool!

**Comment by IDragonfire** [comment]
@brendanjhart I hope so .... 
I corrected the readme ... is this okay?

**Comment by brendanjhart** [comment]
Yes that is great, thankyou for your help :)

**Comment by micheljung** [comment]
And after this is documented, we can just remove the whole thing. The old text can be found in the history either way, and so can the "fixed" version now.

**Pull request merged**
